---
title: "manifesto_analysis"
output: html_document
date: "2023-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
# install.packages("lubridate")
library(lubridate)

civica <- read.csv("manifesto.csv")

# Create a separate dataframe for just Norway, Sweden and Denmark
civica_subset <- dplyr::filter(civica, countryname == "Norway" | countryname == "Sweden" | countryname == "Denmark")

# Identify target variables
vars <- c("countryname", "date", "edate", "partyname", "partyabbrev", "pervote", "per108", "per110", "per601", "per607", "per608", "per7062", "per601_2", "per602_2", "per607_2", "per608_2","rile")

# Select only variables of interest
civica_subset <- civica_subset %>% select(all_of(vars))

# Creating year variable
civica_subset$edate <- as.Date(civica_subset$edate, format = "%d/%m/%Y")
civica_subset$year <- year(civica_subset$edate)

# Change party abbrev to factor variable
civica_subset$partyname <- as.factor(civica_subset$partyname)

# Whether a party is right or left
civica_subset$right <- ifelse(civica_subset$rile>0,1,0)

# Whether a party won highest perc of votes
# Group by year and find the party with the maximum 'pervote' in each year
winners <- civica_subset %>%
  group_by(year) %>%
  slice(which.max(pervote))

# Create a new column 'win' and set it to 1 for the winning party, 0 for others
civica_subset <- civica_subset %>%
  mutate(win = as.numeric(partyname %in% winners$partyname))


#Positive immigration attitudes
civica_subset$im_pos <- ifelse(civica_subset$per602_2>civica_subset$per601_2,1,0)
```

```{r}
# Install and load the 'lubridate' package if you haven't already




# Sweden subset
library(dplyr)
sweden <- civica_subset %>%
  filter(countryname == 'Sweden') %>% 
  filter(year %in% c('2014','2018'))
```

```{r}
library("lmtest")
library("multiwayvcov")
```

```{r}
# Create a new dataset for after 2011
d <- civica_subset[civica_subset$year>2011,]

# A dummy variable called "post" for if it was after policy
d$post <- ifelse(d$year > 2016, 1, 0)

# A variable for the interaction between time and treatment
d$time_treat <- d$post*d$im_pos

summary(lm(pervote ~ post + im_pos + time_treat,data=d))

```



